-- ============================================================================
-- FHA MVP — Storage Buckets & Policies
-- MERGED into Schema.sql (fresh) and live_update.sql (existing DB) per AGENTS.md §35.
-- This file is retained as a pointer only. Do not maintain storage DDL here.
-- Run Schema.sql + live_update.sql instead.
-- ============================================================================
